[NCLSUP-792] Check that revision and tag matches
We want to add a check to make sure that the commit id that the tag we
clones matches the scm revision from the caller.

diff --git a/src/main/resources/application.yaml b/src/main/resources/application.yaml
--- a/src/main/resources/application.yaml
+++ b/src/main/resources/application.yaml
@@ -47,8 +47,14 @@ build-driver:
     echo 'cd %{workingDirectory}/%{projectName}' >> $${HOME}/.bashrc
     set -xe
     cd %{workingDirectory}
-    git clone --branch %{scmRevision} --depth 1 %{scmUrl} %{projectName}
+    git clone --branch %{scmTag} --depth 1 %{scmUrl} %{projectName}
     cd %{projectName}
+    git_commit_id="$(git rev-parse HEAD)"
+    if [[ "%{scmRevision}" != "${git_commit_id}" ]]; then
+      echo "[ERROR] SCM Revision of request doesn't match the commit id from the scm tag"
+      echo "[ERROR] Aborting!"
+      exit 1
+    fi
     %{command}
 
 "%test":
