[NCL-9474] Delete secrets once not needed

diff --git a/src/main/resources/application.yaml b/src/main/resources/application.yaml
--- a/src/main/resources/application.yaml
+++ b/src/main/resources/application.yaml
@@ -61,6 +61,9 @@ build-driver:
       echo "[ERROR] Aborting"
       exit 1
     fi
+    set +xe
+    rm -rf /mnt/secrets/**/* $${HOME}/.ssh/* || { echo "Removal of secrets failed or misconfigured secrets directory. Check build driver configuration." && exit 1 }
+    set -xe
     %{command}
 
 "%test":
